version: '3.8'

services:
  web:
    build: .
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  task_worker:
    container_name: task_worker
    build: .
    entrypoint: celery
    command: -A test_api.celery.app worker --loglevel=DEBUG
    volumes:
      - static_value:/test_api/static/
      - media_value:/test_api/media/
    restart: always
    links:
      - redis
    env_file:
      - .env
    depends_on:
      - redis
      - web

  flower:
    container_name: flower
    build: .
    entrypoint: celery
    command: -A cherry.celery.app flower
    volumes:
      - static_value:/test_api/static/
      - media_value:/test_api/media/
    restart: always
    links:
      - redis
    env_file:
      - .env
    depends_on:
      - task_worker
      - redis
    ports:
      - '5555:5555'

volumes:
  static_value:
  media_value: